import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:project_radar_app/screens/profile/profile_screen.dart';
import 'firebase_options.dart'; // This is generated by `flutterfire configure`


void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}


class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Project RADAR',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: ProfileScreen(
        //onTap: () {}, // Replace with your real logic if needed
      ),
    );
  }
}
